# The title that appears on the tab
title: Thomas Cenci's Gallery

# The title on the web page
full_name: Thomas Cenci

# Integer: Spacing between each photo
spacing: 10

# Integer: Max height for rows
max_height: 600

# Name of your gallery (this will show up at the top of your page and in the RSS feed)
name: Gallery

# Short description (goes below the title; it will also be used in the RSS feed)
description: Photography Portfolio

# Your name, as you want it to appear underneath each post and in the footer
author: Thomas Cenci

# Your email if you want it to be linked on the contact page
author_email: thcenci@gmail.com
